// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrIy3HRCOMZca4u67NkRz-OnZkhEl_K6w',
    appId: '1:581025785752:web:8f1bc2314e12350b66eded',
    messagingSenderId: '581025785752',
    projectId: 'tecommerceapp-2e498',
    authDomain: 'tecommerceapp-2e498.firebaseapp.com',
    storageBucket: 'tecommerceapp-2e498.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeL2PigJXyK0zL2GQgsr36cWeZn0mzTcg',
    appId: '1:581025785752:android:5ae69fe5127f073466eded',
    messagingSenderId: '581025785752',
    projectId: 'tecommerceapp-2e498',
    storageBucket: 'tecommerceapp-2e498.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUmAXaG8d0MAhoUFPG_DE3U0ocOTXZ35E',
    appId: '1:581025785752:ios:0c9d4f87c127c0a666eded',
    messagingSenderId: '581025785752',
    projectId: 'tecommerceapp-2e498',
    storageBucket: 'tecommerceapp-2e498.appspot.com',
    iosClientId: '581025785752-038su08ldv1gaaaa0sfq8i64sf4vki13.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

}